package dev.agentle.feature.insights.ui

import dev.agentle.feature.insights.R
import dev.agentle.jitai.dsl.validation.IssueCode

// Generated from :jitai:dsl IssueCode templates; keep in sync with issue_strings.xml.

/** One localized template of an issue code and the param names of its positional arguments, in order. */
internal data class IssueText(val resId: Int, val params: List<String>)

internal val ISSUE_TEXTS: Map<IssueCode, List<IssueText>> = mapOf(
    IssueCode.E001 to listOf(IssueText(R.string.issue_e001_0, listOf("detail"))),
    IssueCode.E002 to listOf(IssueText(R.string.issue_e002_0, listOf("bytes"))),
    IssueCode.E003 to listOf(IssueText(R.string.issue_e003_0, listOf("offset"))),
    IssueCode.E004 to listOf(IssueText(R.string.issue_e004_0, listOf("value"))),
    IssueCode.E005 to listOf(IssueText(R.string.issue_e005_0, listOf("path"))),
    IssueCode.E006 to listOf(IssueText(R.string.issue_e006_0, listOf("path"))),
    IssueCode.E007 to listOf(IssueText(R.string.issue_e007_0, listOf("path"))),
    IssueCode.E008 to listOf(IssueText(R.string.issue_e008_0, listOf("path", "expected", "actual"))),
    IssueCode.E009 to listOf(IssueText(R.string.issue_e009_0, listOf("path", "allowed", "value"))),
    IssueCode.E090 to listOf(IssueText(R.string.issue_e090_0, listOf("status", "requirement"))),
    IssueCode.E091 to listOf(IssueText(R.string.issue_e091_0, listOf("path", "reason"))),
    IssueCode.E092 to listOf(IssueText(R.string.issue_e092_0, listOf("n")), IssueText(R.string.issue_e092_1, listOf("path"))),
    IssueCode.E099 to listOf(IssueText(R.string.issue_e099_0, listOf("stage"))),
    IssueCode.E010 to listOf(IssueText(R.string.issue_e010_0, listOf("feature", "path"))),
    IssueCode.E011 to listOf(IssueText(R.string.issue_e011_0, listOf("feature", "path", "arg"))),
    IssueCode.E012 to listOf(IssueText(R.string.issue_e012_0, listOf("feature", "path", "arg"))),
    IssueCode.E013 to listOf(IssueText(R.string.issue_e013_0, listOf("arg", "feature", "path", "reason"))),
    IssueCode.E014 to listOf(IssueText(R.string.issue_e014_0, listOf("op", "feature", "valueType", "path", "allowed"))),
    IssueCode.E015 to listOf(IssueText(R.string.issue_e015_0, listOf("path", "expected", "feature", "json"))),
    IssueCode.E016 to listOf(IssueText(R.string.issue_e016_0, listOf("value", "path", "min", "max", "feature"))),
    IssueCode.E017 to listOf(IssueText(R.string.issue_e017_0, listOf("path", "min", "max"))),
    IssueCode.E018 to listOf(IssueText(R.string.issue_e018_0, listOf("path", "max", "n"))),
    IssueCode.E019 to listOf(IssueText(R.string.issue_e019_0, listOf("path", "value"))),
    IssueCode.E020 to listOf(IssueText(R.string.issue_e020_0, listOf("tree", "depth", "max"))),
    IssueCode.E021 to listOf(IssueText(R.string.issue_e021_0, listOf("tree", "n", "max"))),
    IssueCode.E022 to listOf(IssueText(R.string.issue_e022_0, listOf("op", "path"))),
    IssueCode.E023 to listOf(IssueText(R.string.issue_e023_0, listOf("op", "path", "n", "max"))),
    IssueCode.E024 to listOf(IssueText(R.string.issue_e024_0, listOf("value", "path"))),
    IssueCode.E025 to listOf(IssueText(R.string.issue_e025_0, listOf("path", "start"))),
    IssueCode.E026 to listOf(IssueText(R.string.issue_e026_0, listOf("value", "path", "effect", "feature"))),
    IssueCode.E027 to listOf(IssueText(R.string.issue_e027_0, listOf("path", "explanation"))),
    IssueCode.E028 to listOf(IssueText(R.string.issue_e028_0, listOf("kind", "name", "path", "capability"))),
    IssueCode.E029 to listOf(
        IssueText(R.string.issue_e029_0, listOf("since", "path", "start")),
        IssueText(R.string.issue_e029_1, listOf("since", "path", "time")),
        IssueText(R.string.issue_e029_2, listOf("since", "path")),
    ),
    IssueCode.E030 to listOf(IssueText(R.string.issue_e030_0, listOf("value", "path", "allowed"))),
    IssueCode.E031 to listOf(IssueText(R.string.issue_e031_0, listOf("path"))),
    IssueCode.E032 to listOf(IssueText(R.string.issue_e032_0, listOf("n"))),
    IssueCode.E033 to listOf(IssueText(R.string.issue_e033_0, listOf("min", "origin", "n"))),
    IssueCode.E034 to listOf(IssueText(R.string.issue_e034_0, listOf("n"))),
    IssueCode.E035 to listOf(IssueText(R.string.issue_e035_0, listOf("path"))),
    IssueCode.E036 to listOf(IssueText(R.string.issue_e036_0, listOf("n"))),
    IssueCode.E037 to listOf(IssueText(R.string.issue_e037_0, listOf("triggerType"))),
    IssueCode.E038 to listOf(IssueText(R.string.issue_e038_0, listOf())),
    IssueCode.E039 to listOf(IssueText(R.string.issue_e039_0, listOf("time", "start", "end"))),
    IssueCode.E040 to listOf(IssueText(R.string.issue_e040_0, listOf("field"))),
    IssueCode.E041 to listOf(IssueText(R.string.issue_e041_0, listOf("min", "origin", "n"))),
    IssueCode.E042 to listOf(IssueText(R.string.issue_e042_0, listOf("max", "origin", "n"))),
    IssueCode.E043 to listOf(IssueText(R.string.issue_e043_0, listOf("max", "origin", "n"))),
    IssueCode.E044 to listOf(IssueText(R.string.issue_e044_0, listOf("w", "d"))),
    IssueCode.E045 to listOf(IssueText(R.string.issue_e045_0, listOf("max", "origin", "n"))),
    IssueCode.E046 to listOf(IssueText(R.string.issue_e046_0, listOf())),
    IssueCode.E047 to listOf(IssueText(R.string.issue_e047_0, listOf("n"))),
    IssueCode.E048 to listOf(
        IssueText(R.string.issue_e048_0, listOf("n")),
        IssueText(R.string.issue_e048_1, listOf("n")),
        IssueText(R.string.issue_e048_2, listOf("range", "n")),
    ),
    IssueCode.E049 to listOf(IssueText(R.string.issue_e049_0, listOf())),
    IssueCode.E050 to listOf(IssueText(R.string.issue_e050_0, listOf())),
    IssueCode.E051 to listOf(IssueText(R.string.issue_e051_0, listOf())),
    IssueCode.E052 to listOf(IssueText(R.string.issue_e052_0, listOf())),
    IssueCode.E053 to listOf(IssueText(R.string.issue_e053_0, listOf("field", "expected"))),
    IssueCode.E054 to listOf(IssueText(R.string.issue_e054_0, listOf("field"))),
    IssueCode.E055 to listOf(IssueText(R.string.issue_e055_0, listOf("triggerType"))),
    IssueCode.E056 to listOf(IssueText(R.string.issue_e056_0, listOf("target", "path", "reason"))),
    IssueCode.E057 to listOf(IssueText(R.string.issue_e057_0, listOf())),
    IssueCode.E058 to listOf(IssueText(R.string.issue_e058_0, listOf("path", "n"))),
    IssueCode.E060 to listOf(IssueText(R.string.issue_e060_0, listOf("path", "min", "max", "n"))),
    IssueCode.E061 to listOf(IssueText(R.string.issue_e061_0, listOf("path", "match"))),
    IssueCode.E062 to listOf(IssueText(R.string.issue_e062_0, listOf("path", "category", "match"))),
    IssueCode.E063 to listOf(IssueText(R.string.issue_e063_0, listOf("name", "path"))),
    IssueCode.E064 to listOf(IssueText(R.string.issue_e064_0, listOf("name", "path"))),
    IssueCode.E065 to listOf(IssueText(R.string.issue_e065_0, listOf("name", "path"))),
    IssueCode.E066 to listOf(IssueText(R.string.issue_e066_0, listOf("path", "hex"))),
    IssueCode.E067 to listOf(IssueText(R.string.issue_e067_0, listOf("path", "snippet"))),
    IssueCode.E068 to listOf(IssueText(R.string.issue_e068_0, listOf("assetId", "path"))),
    IssueCode.E069 to listOf(IssueText(R.string.issue_e069_0, listOf("type", "channel"))),
    IssueCode.E070 to listOf(IssueText(R.string.issue_e070_0, listOf())),
    IssueCode.E071 to listOf(IssueText(R.string.issue_e071_0, listOf("metric", "role"))),
    IssueCode.E072 to listOf(IssueText(R.string.issue_e072_0, listOf("metric", "path", "reason"))),
    IssueCode.E073 to listOf(IssueText(R.string.issue_e073_0, listOf("metric", "range", "n"))),
    IssueCode.E081 to listOf(IssueText(R.string.issue_e081_0, listOf("value", "path"))),
    IssueCode.C01 to listOf(IssueText(R.string.issue_c01_0, listOf("appLabel"))),
    IssueCode.C02 to listOf(IssueText(R.string.issue_c02_0, listOf()), IssueText(R.string.issue_c02_1, listOf())),
    IssueCode.C03 to listOf(IssueText(R.string.issue_c03_0, listOf("start", "end")), IssueText(R.string.issue_c03_1, listOf())),
    IssueCode.C04 to listOf(IssueText(R.string.issue_c04_0, listOf("text"))),
    IssueCode.C05 to listOf(IssueText(R.string.issue_c05_0, listOf("feature"))),
    IssueCode.W01 to listOf(IssueText(R.string.issue_w01_0, listOf("name"))),
    IssueCode.W02 to listOf(IssueText(R.string.issue_w02_0, listOf("feature"))),
    IssueCode.W03 to listOf(IssueText(R.string.issue_w03_0, listOf("access"))),
    IssueCode.W04 to listOf(IssueText(R.string.issue_w04_0, listOf("start", "end"))),
    IssueCode.W05 to listOf(IssueText(R.string.issue_w05_0, listOf("n", "period"))),
    IssueCode.W06 to listOf(IssueText(R.string.issue_w06_0, listOf("name"))),
    IssueCode.W07 to listOf(IssueText(R.string.issue_w07_0, listOf("feature"))),
    IssueCode.W08 to listOf(IssueText(R.string.issue_w08_0, listOf("event"))),
    IssueCode.W09 to listOf(IssueText(R.string.issue_w09_0, listOf("op", "value", "path"))),
    IssueCode.W10 to listOf(IssueText(R.string.issue_w10_0, listOf())),
)
