package dev.agentle.core.model

import kotlinx.serialization.Serializable

/**
 * Closed set of normalized event types (docs/ARCHITECTURE.md §5.1). New types are appended, never renamed: the
 * enum name is persisted. [category] decides AI-sharing gates and deletion groups.
 */
@Serializable
public enum class EventType(public val category: DataCategory) {
    // Apps and screen
    APP_FOREGROUND(DataCategory.APP_USAGE),
    APP_BACKGROUND(DataCategory.APP_USAGE),
    APP_SESSION(DataCategory.APP_USAGE),
    SCREEN_ON(DataCategory.SCREEN),
    SCREEN_OFF(DataCategory.SCREEN),
    SCREEN_SESSION(DataCategory.SCREEN),
    DEVICE_UNLOCK(DataCategory.SCREEN),
    DEVICE_LOCK(DataCategory.SCREEN),

    // Notifications
    NOTIFICATION_POSTED(DataCategory.NOTIFICATIONS),
    NOTIFICATION_REMOVED(DataCategory.NOTIFICATIONS),

    // Location
    LOCATION_SAMPLE(DataCategory.LOCATION),
    LOCATION_VISIT(DataCategory.LOCATION),

    // Activity, health, sleep, body
    STEP_SAMPLE(DataCategory.ACTIVITY),
    DISTANCE_SAMPLE(DataCategory.ACTIVITY),
    FLOORS_SAMPLE(DataCategory.ACTIVITY),
    CALORIES_SAMPLE(DataCategory.ACTIVITY),
    ACTIVITY(DataCategory.ACTIVITY),
    EXERCISE_SESSION(DataCategory.ACTIVITY),
    HEART_RATE(DataCategory.HEART),
    RESTING_HEART_RATE(DataCategory.HEART),
    SLEEP_SESSION(DataCategory.SLEEP),
    WEIGHT(DataCategory.BODY),
    BODY_FAT(DataCategory.BODY),
    WEARABLE_DEVICE(DataCategory.DEVICE_STATE),

    // Device state
    BATTERY_SAMPLE(DataCategory.DEVICE_STATE),
    CHARGING_STARTED(DataCategory.DEVICE_STATE),
    CHARGING_STOPPED(DataCategory.DEVICE_STATE),
    POWER_STATE_CHANGED(DataCategory.DEVICE_STATE),
    CONNECTIVITY_CHANGED(DataCategory.DEVICE_STATE),
    AIRPLANE_MODE_CHANGED(DataCategory.DEVICE_STATE),
    BLUETOOTH_STATE_CHANGED(DataCategory.DEVICE_STATE),
    BLUETOOTH_CONNECTED(DataCategory.DEVICE_STATE),
    BLUETOOTH_DISCONNECTED(DataCategory.DEVICE_STATE),
    AUDIO_STATE(DataCategory.DEVICE_STATE),
    HEADSET_CONNECTED(DataCategory.DEVICE_STATE),
    HEADSET_DISCONNECTED(DataCategory.DEVICE_STATE),
    DND_CHANGED(DataCategory.DEVICE_STATE),
    TIMEZONE_CHANGED(DataCategory.DEVICE_STATE),
    TIME_CHANGED(DataCategory.DEVICE_STATE),
    LOCALE_CHANGED(DataCategory.DEVICE_STATE),
    BOOT_COMPLETED(DataCategory.DEVICE_STATE),
    SHUTDOWN(DataCategory.DEVICE_STATE),

    // Calendar, communication, media
    CALENDAR_EVENT(DataCategory.CALENDAR),
    CALL_EVENT(DataCategory.COMMUNICATION),
    MEDIA_CREATED(DataCategory.MEDIA),

    // User input
    USER_LOG(DataCategory.USER_LOGS),

    // Generated by Agentle itself
    JITAI_TRIGGERED(DataCategory.INTERVENTIONS),
    JITAI_DELIVERED(DataCategory.INTERVENTIONS),
    JITAI_OPENED(DataCategory.INTERVENTIONS),
    JITAI_DISMISSED(DataCategory.INTERVENTIONS),
    INSIGHT_CREATED(DataCategory.INSIGHTS),
    IMAGE_GENERATED(DataCategory.GENERATED_MEDIA),
    VOICE_GENERATED(DataCategory.GENERATED_MEDIA),
    VIDEO_GENERATED(DataCategory.GENERATED_MEDIA),

    // Appended later (enum names are persisted, so new types go at the end)

    /** The next alarm clock changed or was sampled (see [NextAlarmPayload]). */
    NEXT_ALARM_CHANGED(DataCategory.DEVICE_STATE),

    /** An app standby bucket changed or was sampled (see [StandbyBucketPayload]). */
    STANDBY_BUCKET_CHANGED(DataCategory.DEVICE_STATE),

    /** Device storage sample (see [StoragePayload]). */
    STORAGE_SAMPLE(DataCategory.DEVICE_STATE),
}

/**
 * Data categories. They group event types for AI-sharing consent (a request may only contain allowed categories),
 * for the Permission Center and for retention/deletion. [sensitiveByDefault] categories are never shared with AI
 * unless the user explicitly enables them.
 */
@Serializable
public enum class DataCategory(public val sensitiveByDefault: Boolean) {
    APP_USAGE(false),
    SCREEN(false),
    NOTIFICATIONS(false),
    NOTIFICATION_CONTENT(true),
    LOCATION(true),
    ACTIVITY(false),
    HEART(true),
    SLEEP(false),
    BODY(true),
    DEVICE_STATE(false),
    CALENDAR(true),
    COMMUNICATION(true),
    MEDIA(true),
    USER_LOGS(true),
    GOALS(false),
    INTERVENTIONS(false),
    INSIGHTS(false),
    GENERATED_MEDIA(false),
}
