package dev.agentle.ai.api.validation

import dev.agentle.ai.api.OutputSchema
import kotlinx.coroutines.CancellationException
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

/** One error reported by the rule language's own validator: a code such as `E042` and a JSON pointer. */
public data class RuleIssue(val code: String, val path: String, val stage: ValidationStage = ValidationStage.S6_SEMANTIC)

/** The verdict of a [JitaiRuleCheck]. Confirm items and warnings are not errors and are not reported here. */
public sealed interface RuleCheckResult<out T : Any> {
    public data class Accepted<out T : Any>(val proposal: T) : RuleCheckResult<T>

    public data class Rejected(val issues: List<RuleIssue>) : RuleCheckResult<Nothing> {
        init {
            require(issues.isNotEmpty()) { "a rejection has at least one issue" }
        }
    }
}

/**
 * The in-depth check of a JITAI proposal by the owner of the rule language (`:jitai:dsl`, R10 section 11: conditions,
 * triggers, limits, placeholders, app-owned fields). The app's wiring adapts it, because `:jitai:dsl` does not depend on
 * `:ai:api`. It receives the document after S0-S3 and returns the decoded proposal or its errors (codes and paths
 * only, never messages: R10 messages can quote the proposal).
 */
public fun interface JitaiRuleCheck<out T : Any> {
    public fun check(document: JsonObject): RuleCheckResult<T>
}

/**
 * JitaiProposalSchema v1 (R10 section 13.3), the reply of the natural-language rule builder. This module checks the
 * envelope (S4 on every key except the draft, then E090-E092) and runs [AiTextPolicy] on every text field R10 section
 * 11.6 lists, with placeholders allowed only in template text. The draft under `/jitai` is validated by the
 * [JitaiRuleCheck] given to [validator]; without one, a proposal cannot be routed and fails closed (E110). Issues of
 * both are merged; paths from the rule check are reduced to known schema keys.
 *
 * Number provenance (L9) for a proposal: the request context plus the numbers and `HH:mm` times of the rule itself
 * (the thresholds the model chose, which the user sees in the rendered rule), each also read as minutes (360 as
 * "6 hours"). Callers usually pass the envelope's instructions as template text, since the R10 section 13.6 examples
 * quote the contract's own numbers.
 */
public object JitaiProposalSchema {
    public const val NAME: String = "JitaiProposalSchema"
    public const val VERSION: Int = 1
    public const val MAX_BYTES: Int = 16_384
    public const val MAX_QUESTIONS: Int = 3
    public const val MIN_OPTIONS: Int = 2
    public const val MAX_OPTIONS: Int = 4
    public const val MAX_ASSUMPTIONS: Int = 5

    /** The published schema text is generated by `:jitai:dsl` (R10 section 13.3); this identity carries none. */
    public val SCHEMA: OutputSchema = OutputSchema(NAME, VERSION, jsonSchema = null)

    public val STATUSES: List<String> = listOf("OK", "NEEDS_CLARIFICATION", "UNSUPPORTED")
    public val UNSUPPORTED_REASONS: List<String> = listOf(
        "NEEDS_UNAVAILABLE_DATA",
        "NEEDS_FINER_TIMING",
        "NEEDS_UNAVAILABLE_ACTION",
        "NOT_A_REMINDER",
        "HEALTH_OR_SAFETY",
        "OTHER",
    )

    public val NAME_RULES: TextRules = TextRules(maxChars = 60, maxSentences = 1)
    public val DESCRIPTION: TextRules = TextRules(maxChars = 280, maxSentences = 2)
    public val STATIC_TITLE: TextRules = TextRules(maxChars = 60, maxSentences = 2)
    public val STATIC_BODY: TextRules = TextRules(maxChars = 240, maxSentences = 3)
    public val TEMPLATE_TITLE: TextRules = STATIC_TITLE.copy(placeholdersAllowed = true)
    public val TEMPLATE_BODY: TextRules = STATIC_BODY.copy(placeholdersAllowed = true)
    public val GOAL: TextRules = TextRules(maxChars = 200, maxSentences = 2)
    public val ASSUMPTION: TextRules = TextRules(maxChars = 200, maxSentences = 2)
    public val QUESTION: TextRules = TextRules(maxChars = 200, maxSentences = 2)
    public val OPTION: TextRules = TextRules(maxChars = 60, maxSentences = 1)
    public val DETAIL: TextRules = TextRules(maxChars = 200, maxSentences = 2, minChars = 0)

    private val ASSUMPTION_PATH = Regex("^/jitai(/[A-Za-z0-9_]+)*$")
    private const val MAX_ASSUMPTION_PATH = 200
    private val HHMM = Regex("^([01][0-9]|2[0-3]):[0-5][0-9]$")
    private val CODE = Regex("^[ECW][0-9]{3}$")
    private val INDEX = Regex("^(0|[1-9][0-9]{0,3})$")
    private val NON_TEXT_CONTENT_KEYS = setOf("type", "tone", "selection", "assetId")

    /** Every key of R10 section 13.3 plus the app-owned keys of E005: the only key text a reported path may contain. */
    public val KNOWN_KEYS: Set<String> = setOf(
        "schemaVersion", "status", "unsupported", "questions", "assumptions", "jitai", "reason", "detail", "id", "text", "options",
        "path", "name", "description", "kind", "category", "trigger", "activeWindow", "conditions", "contextRequirements",
        "delivery", "content", "cooldownMinutes", "maxPerDay", "maxPerWeek", "priority", "snooze", "expiresInDays", "outcome",
        "suppression", "type", "events", "debounceSeconds", "everyMinutes", "times", "maxLatenessMinutes", "start", "end", "days",
        "of", "feature", "args", "value", "min", "max", "values", "onUnknown", "package", "appLabel", "since", "channel",
        "quietHoursPolicy", "notificationTimeoutMinutes", "title", "body", "items", "selection", "goal", "tone", "fallback",
        "assetId", "caption", "mode", "proximal", "distal", "metric", "windowMinutes", "categories", "version", "enabled",
        "createdBy", "createdAt", "modifiedAt", "expiresAt", "experiment", "userConfirmedUnknownOverrides", "provenance",
        "contentHash", "deliveryDeadlineMinutes", "jitaiIds",
    )

    /** The envelope; the draft is opaque here and checked by the [JitaiRuleCheck]. */
    public val ENVELOPE: SchemaNode.ObjectNode = SchemaNode.ObjectNode(
        linkedMapOf(
            "schemaVersion" to SchemaNode.ConstNode(VERSION.toLong(), OutputCodes.UNSUPPORTED_SCHEMA_VERSION),
            "status" to SchemaNode.StringNode(allowed = STATUSES),
            "unsupported" to SchemaNode.ObjectNode(
                linkedMapOf(
                    "reason" to SchemaNode.StringNode(allowed = UNSUPPORTED_REASONS),
                    "detail" to SchemaNode.StringNode(nullable = true),
                ),
                nullable = true,
            ),
            "questions" to SchemaNode.ArrayNode(
                SchemaNode.ObjectNode(
                    linkedMapOf(
                        "id" to SchemaNode.StringNode(allowed = listOf("q1", "q2", "q3")),
                        "text" to SchemaNode.StringNode(),
                        "options" to SchemaNode.ArrayNode(SchemaNode.StringNode()),
                    ),
                ),
            ),
            "assumptions" to
                SchemaNode.ArrayNode(
                    SchemaNode.ObjectNode(linkedMapOf("path" to SchemaNode.StringNode(), "text" to SchemaNode.StringNode())),
                ),
            "jitai" to SchemaNode.AnyObjectNode(nullable = true),
        ),
    )

    /** The validator of proposals whose draft [check] validates in depth. */
    public fun <T : Any> validator(check: JitaiRuleCheck<T>): SchemaValidator<T> = Validator(check)

    /** A pointer whose segments are known keys or array indexes; anything else becomes `*`. */
    public fun sanitizePath(path: String): String {
        if (path.isEmpty()) return ""
        if (!path.startsWith('/')) return "/*"
        return path.split('/').drop(1).joinToString("") { segment ->
            val key = segment.replace("~1", "/").replace("~0", "~")
            "/" + if (key in KNOWN_KEYS || INDEX.matches(key)) segment else "*"
        }
    }

    private class Validator<T : Any>(private val check: JitaiRuleCheck<T>) : SchemaValidator<T> {
        override val schema: OutputSchema = SCHEMA
        override val maxBytes: Int = MAX_BYTES

        override fun validateDocument(document: JsonObject, context: OutputValidationContext): OutputValidation<T> {
            val issues = SchemaWalker.walk(ENVELOPE, document).toMutableList()
            if (issues.isEmpty()) {
                issues += envelopeIssues(document)
                val proposalContext = context.copy(provenance = context.provenance?.let { it + ruleNumbers(document["jitai"]) })
                issues += textPolicyIssues(textFields(document), proposalContext)
            }
            var proposal: T? = null
            when (val verdict = runCheck(document)) {
                is RuleCheckResult.Accepted -> proposal = verdict.proposal
                is RuleCheckResult.Rejected -> issues += verdict.issues.map(::toIssue)
            }
            return when {
                issues.isNotEmpty() -> OutputValidation.invalid(schema, issues)
                proposal != null -> OutputValidation.Valid(proposal, schema)
                else -> OutputValidation.invalid(schema, listOf(ValidationIssue(OutputCodes.INTERNAL, "", ValidationStage.S6_SEMANTIC)))
            }
        }

        private fun runCheck(document: JsonObject): RuleCheckResult<T> = try {
            check.check(document)
        } catch (e: CancellationException) {
            throw e
        } catch (expected: RuntimeException) {
            // A failing rule check never accepts; its message may quote the proposal and is dropped (privacy-ai-11).
            RuleCheckResult.Rejected(listOf(RuleIssue(OutputCodes.INTERNAL, "")))
        }

        private fun toIssue(issue: RuleIssue): ValidationIssue =
            ValidationIssue(if (CODE.matches(issue.code)) issue.code else OutputCodes.INTERNAL, sanitizePath(issue.path), issue.stage)
    }

    private fun envelopeIssues(document: JsonObject): List<ValidationIssue> {
        val issues = mutableListOf<ValidationIssue>()
        fun add(code: String, path: String) {
            issues += ValidationIssue(code, path, ValidationStage.S6_SEMANTIC)
        }
        val status = (document["status"] as JsonPrimitive).content
        val questions = document["questions"] as JsonArray
        val assumptions = document["assumptions"] as JsonArray
        val hasDraft = document["jitai"] !is JsonNull
        val hasUnsupported = document["unsupported"] !is JsonNull
        val consistent = when (status) {
            "OK" -> hasDraft && questions.isEmpty() && !hasUnsupported
            "NEEDS_CLARIFICATION" -> !hasDraft && questions.size in 1..MAX_QUESTIONS
            else -> !hasDraft && hasUnsupported
        }
        if (!consistent) add(OutputCodes.ENVELOPE_INCONSISTENT, "/status")
        val ids = questions.map { ((it as JsonObject)["id"] as JsonPrimitive).content }
        if (questions.size > MAX_QUESTIONS || ids.toSet().size != ids.size) add(OutputCodes.QUESTIONS_INVALID, "/questions")
        questions.forEachIndexed { index, question ->
            val options = (question as JsonObject)["options"] as JsonArray
            if (options.size !in MIN_OPTIONS..MAX_OPTIONS) add(OutputCodes.QUESTIONS_INVALID, "/questions/$index/options")
        }
        if (assumptions.size > MAX_ASSUMPTIONS) add(OutputCodes.ASSUMPTIONS_INVALID, "/assumptions")
        assumptions.forEachIndexed { index, assumption ->
            val path = ((assumption as JsonObject)["path"] as JsonPrimitive).content
            if (path.length > MAX_ASSUMPTION_PATH ||
                !ASSUMPTION_PATH.matches(path)
            ) {
                add(OutputCodes.PATTERN_MISMATCH, "/assumptions/$index/path")
            }
        }
        return issues
    }

    /** The R10 section 11.6 text fields of the envelope and the draft. */
    private fun textFields(document: JsonObject): List<TextField> = buildList {
        (document["unsupported"] as? JsonObject)?.let { unsupported ->
            stringAt(unsupported, "detail")?.let { add(TextField("/unsupported/detail", it, DETAIL)) }
        }
        (document["questions"] as JsonArray).forEachIndexed { index, question ->
            question as JsonObject
            stringAt(question, "text")?.let { add(TextField("/questions/$index/text", it, QUESTION)) }
            (question["options"] as JsonArray).forEachIndexed { option, value ->
                (value as? JsonPrimitive)?.takeIf {
                    it.isString
                }?.let { add(TextField("/questions/$index/options/$option", it.content, OPTION)) }
            }
        }
        (document["assumptions"] as JsonArray).forEachIndexed { index, assumption ->
            stringAt(assumption as JsonObject, "text")?.let { add(TextField("/assumptions/$index/text", it, ASSUMPTION)) }
        }
        val draft = document["jitai"] as? JsonObject ?: return@buildList
        stringAt(draft, "name")?.let { add(TextField("/jitai/name", it, NAME_RULES)) }
        stringAt(draft, "description")?.let { add(TextField("/jitai/description", it, DESCRIPTION)) }
        (draft["content"] as? JsonObject)?.let { content ->
            val templated = stringAt(content, "type") != "static"
            contentFields(content, "/jitai/content", templated, this)
        }
    }

    /**
     * Every string under the content strategy except its codes: `title` and `body` as title and body text (placeholders
     * allowed unless the strategy is `static`), `goal` as plain text, any other key as body text. Unknown keys become
     * `*` in the path; the rule check rejects them.
     */
    private fun contentFields(node: JsonObject, path: String, templated: Boolean, out: MutableList<TextField>) {
        node.forEach { (key, value) ->
            val childPath = "$path/" + if (key in KNOWN_KEYS) key else "*"
            when (value) {
                is JsonObject -> contentFields(value, childPath, templated, out)

                is JsonArray -> value.forEachIndexed { index, item ->
                    if (item is JsonObject) contentFields(item, "$childPath/$index", templated, out)
                }

                is JsonPrimitive -> if (value.isString &&
                    key !in NON_TEXT_CONTENT_KEYS
                ) {
                    out += TextField(childPath, value.content, contentRules(key, templated))
                }
            }
        }
    }

    private fun contentRules(key: String, templated: Boolean): TextRules = when {
        key == "goal" -> GOAL
        key == "title" -> if (templated) TEMPLATE_TITLE else STATIC_TITLE
        else -> if (templated) TEMPLATE_BODY else STATIC_BODY
    }

    /** Numbers and `HH:mm` times of the rule (not of its text), each number also read as minutes. */
    private fun ruleNumbers(draft: JsonElement?): NumberProvenance {
        val numbers = mutableListOf<Number>()
        val times = mutableListOf<String>()
        fun visit(element: JsonElement?) {
            when (element) {
                is JsonObject -> element.values.forEach(::visit)

                is JsonArray -> element.forEach(::visit)

                is JsonPrimitive -> when {
                    element.isString -> if (HHMM.matches(element.content)) times += element.content
                    else -> element.content.toBigDecimalOrNull()?.let { numbers += it }
                }

                else -> Unit
            }
        }
        visit(draft)
        return NumberProvenance.ofMeasurements(numbers, minutes = true) + NumberProvenance.ofTimes(times)
    }

    private fun stringAt(node: JsonObject, key: String): String? = (node[key] as? JsonPrimitive)?.takeIf { it.isString }?.content
}
